AllCops:
  Exclude:
    - 'bin/*'
    - 'config/environments/*'
    -
Style/Documentation:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false
inherit_gem:
  rubocop-discourse: default.yml

