services:
  - type: web
    name: current_rails_ebwiki
    env: ruby
    buildCommand: "bundle install && rake db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ebwiki_production

      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-ebwiki
          property: connectionString
    region: oregon

  # Redis 1 - all fields defined
  - type: redis
    name: redis_ebwiki
    ipAllowList: # required - allow external connections from only these CIDR blocks
      - source: 24.187.55.144
        description: office
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter instance type)
    maxmemoryPolicy: allkeys-lru # optional (defaults to allkeys-lru)


databases:
  - name: ebwiki_production
    databaseName: ebwiki_7_production # optional (Render may add a suffix)
    ipAllowList: [] # only allow internal connections

